//
// Porymap-compatible version of region_map_sections.h
// Porymap's parser only understands #define statements, not C enums.
// This file is for Porymap use only. The build uses the auto-generated enum file.
//
// Auto-generated values match region_map_sections.h content.

#ifndef GUARD_CONSTANTS_REGION_MAP_SECTIONS_PORYMAP_H
#define GUARD_CONSTANTS_REGION_MAP_SECTIONS_PORYMAP_H

#define MAPSEC_LITTLEROOT_TOWN                   0
#define MAPSEC_OLDALE_TOWN                       1
#define MAPSEC_DEWFORD_TOWN                      2
#define MAPSEC_LAVARIDGE_TOWN                    3
#define MAPSEC_FALLARBOR_TOWN                    4
#define MAPSEC_VERDANTURF_TOWN                   5
#define MAPSEC_PACIFIDLOG_TOWN                   6
#define MAPSEC_PETALBURG_CITY                    7
#define MAPSEC_SLATEPORT_CITY                    8
#define MAPSEC_MAUVILLE_CITY                     9
#define MAPSEC_RUSTBORO_CITY                     10
#define MAPSEC_FORTREE_CITY                      11
#define MAPSEC_LILYCOVE_CITY                     12
#define MAPSEC_MOSSDEEP_CITY                     13
#define MAPSEC_SOOTOPOLIS_CITY                   14
#define MAPSEC_EVER_GRANDE_CITY                  15
#define MAPSEC_ROUTE_101                         16
#define MAPSEC_ROUTE_102                         17
#define MAPSEC_ROUTE_103                         18
#define MAPSEC_ROUTE_104                         19
#define MAPSEC_ROUTE_105                         20
#define MAPSEC_ROUTE_106                         21
#define MAPSEC_ROUTE_107                         22
#define MAPSEC_ROUTE_108                         23
#define MAPSEC_ROUTE_109                         24
#define MAPSEC_ROUTE_110                         25
#define MAPSEC_ROUTE_111                         26
#define MAPSEC_ROUTE_112                         27
#define MAPSEC_ROUTE_113                         28
#define MAPSEC_ROUTE_114                         29
#define MAPSEC_ROUTE_115                         30
#define MAPSEC_ROUTE_116                         31
#define MAPSEC_ROUTE_117                         32
#define MAPSEC_ROUTE_118                         33
#define MAPSEC_ROUTE_119                         34
#define MAPSEC_ROUTE_120                         35
#define MAPSEC_ROUTE_121                         36
#define MAPSEC_ROUTE_122                         37
#define MAPSEC_ROUTE_123                         38
#define MAPSEC_ROUTE_124                         39
#define MAPSEC_ROUTE_125                         40
#define MAPSEC_ROUTE_126                         41
#define MAPSEC_ROUTE_127                         42
#define MAPSEC_ROUTE_128                         43
#define MAPSEC_ROUTE_129                         44
#define MAPSEC_ROUTE_130                         45
#define MAPSEC_ROUTE_131                         46
#define MAPSEC_ROUTE_132                         47
#define MAPSEC_ROUTE_133                         48
#define MAPSEC_ROUTE_134                         49
#define MAPSEC_UNDERWATER_124                    50
#define MAPSEC_UNDERWATER_126                    51
#define MAPSEC_UNDERWATER_127                    52
#define MAPSEC_UNDERWATER_128                    53
#define MAPSEC_UNDERWATER_SOOTOPOLIS             54
#define MAPSEC_GRANITE_CAVE                      55
#define MAPSEC_MT_CHIMNEY                        56
#define MAPSEC_SAFARI_ZONE                       57
#define MAPSEC_BATTLE_FRONTIER                   58
#define MAPSEC_PETALBURG_WOODS                   59
#define MAPSEC_RUSTURF_TUNNEL                    60
#define MAPSEC_ABANDONED_SHIP                    61
#define MAPSEC_NEW_MAUVILLE                      62
#define MAPSEC_METEOR_FALLS                      63
#define MAPSEC_METEOR_FALLS2                     64
#define MAPSEC_MT_PYRE                           65
#define MAPSEC_AQUA_HIDEOUT_OLD                  66
#define MAPSEC_SHOAL_CAVE                        67
#define MAPSEC_SEAFLOOR_CAVERN                   68
#define MAPSEC_UNDERWATER_SEAFLOOR_CAVERN        69
#define MAPSEC_VICTORY_ROAD                      70
#define MAPSEC_MIRAGE_ISLAND                     71
#define MAPSEC_CAVE_OF_ORIGIN                    72
#define MAPSEC_SOUTHERN_ISLAND                   73
#define MAPSEC_FIERY_PATH                        74
#define MAPSEC_FIERY_PATH2                       75
#define MAPSEC_JAGGED_PASS                       76
#define MAPSEC_JAGGED_PASS2                      77
#define MAPSEC_SEALED_CHAMBER                    78
#define MAPSEC_UNDERWATER_SEALED_CHAMBER         79
#define MAPSEC_SCORCHED_SLAB                     80
#define MAPSEC_ISLAND_CAVE                       81
#define MAPSEC_DESERT_RUINS                      82
#define MAPSEC_ANCIENT_TOMB                      83
#define MAPSEC_INSIDE_OF_TRUCK                   84
#define MAPSEC_SKY_PILLAR                        85
#define MAPSEC_SECRET_BASE                       86
#define MAPSEC_DYNAMIC                           87
#define MAPSEC_PALLET_TOWN                       88
#define MAPSEC_VIRIDIAN_CITY                     89
#define MAPSEC_PEWTER_CITY                       90
#define MAPSEC_CERULEAN_CITY                     91
#define MAPSEC_LAVENDER_TOWN                     92
#define MAPSEC_VERMILION_CITY                    93
#define MAPSEC_CELADON_CITY                      94
#define MAPSEC_FUCHSIA_CITY                      95
#define MAPSEC_CINNABAR_ISLAND                   96
#define MAPSEC_INDIGO_PLATEAU                    97
#define MAPSEC_SAFFRON_CITY                      98
#define MAPSEC_ROUTE_4_POKECENTER                99
#define MAPSEC_ROUTE_10_POKECENTER               100
#define MAPSEC_ROUTE_1                           101
#define MAPSEC_ROUTE_2                           102
#define MAPSEC_ROUTE_3                           103
#define MAPSEC_ROUTE_4                           104
#define MAPSEC_ROUTE_5                           105
#define MAPSEC_ROUTE_6                           106
#define MAPSEC_ROUTE_7                           107
#define MAPSEC_ROUTE_8                           108
#define MAPSEC_ROUTE_9                           109
#define MAPSEC_ROUTE_10                          110
#define MAPSEC_ROUTE_11                          111
#define MAPSEC_ROUTE_12                          112
#define MAPSEC_ROUTE_13                          113
#define MAPSEC_ROUTE_14                          114
#define MAPSEC_ROUTE_15                          115
#define MAPSEC_ROUTE_16                          116
#define MAPSEC_ROUTE_17                          117
#define MAPSEC_ROUTE_18                          118
#define MAPSEC_ROUTE_19                          119
#define MAPSEC_ROUTE_20                          120
#define MAPSEC_ROUTE_21                          121
#define MAPSEC_ROUTE_22                          122
#define MAPSEC_ROUTE_23                          123
#define MAPSEC_ROUTE_24                          124
#define MAPSEC_ROUTE_25                          125
#define MAPSEC_VIRIDIAN_FOREST                   126
#define MAPSEC_MT_MOON                           127
#define MAPSEC_S_S_ANNE                          128
#define MAPSEC_UNDERGROUND_PATH                  129
#define MAPSEC_UNDERGROUND_PATH_2                130
#define MAPSEC_DIGLETTS_CAVE                     131
#define MAPSEC_KANTO_VICTORY_ROAD                132
#define MAPSEC_ROCKET_HIDEOUT                    133
#define MAPSEC_SILPH_CO                          134
#define MAPSEC_POKEMON_MANSION                   135
#define MAPSEC_KANTO_SAFARI_ZONE                 136
#define MAPSEC_POKEMON_LEAGUE                    137
#define MAPSEC_ROCK_TUNNEL                       138
#define MAPSEC_SEAFOAM_ISLANDS                   139
#define MAPSEC_POKEMON_TOWER                     140
#define MAPSEC_CERULEAN_CAVE                     141
#define MAPSEC_POWER_PLANT                       142
#define MAPSEC_ONE_ISLAND                        143
#define MAPSEC_TWO_ISLAND                        144
#define MAPSEC_THREE_ISLAND                      145
#define MAPSEC_FOUR_ISLAND                       146
#define MAPSEC_FIVE_ISLAND                       147
#define MAPSEC_SEVEN_ISLAND                      148
#define MAPSEC_SIX_ISLAND                        149
#define MAPSEC_KINDLE_ROAD                       150
#define MAPSEC_TREASURE_BEACH                    151
#define MAPSEC_CAPE_BRINK                        152
#define MAPSEC_BOND_BRIDGE                       153
#define MAPSEC_THREE_ISLE_PORT                   154
#define MAPSEC_RESORT_GORGEOUS                   155
#define MAPSEC_WATER_LABYRINTH                   156
#define MAPSEC_FIVE_ISLE_MEADOW                  157
#define MAPSEC_MEMORIAL_PILLAR                   158
#define MAPSEC_OUTCAST_ISLAND                    159
#define MAPSEC_GREEN_PATH                        160
#define MAPSEC_WATER_PATH                        161
#define MAPSEC_RUIN_VALLEY                       162
#define MAPSEC_TRAINER_TOWER                     163
#define MAPSEC_CANYON_ENTRANCE                   164
#define MAPSEC_SEVAULT_CANYON                    165
#define MAPSEC_TANOBY_RUINS                      166
#define MAPSEC_SEVII_ISLE_22                     167
#define MAPSEC_SEVII_ISLE_23                     168
#define MAPSEC_SEVII_ISLE_24                     169
#define MAPSEC_NAVEL_ROCK_FRLG                   170
#define MAPSEC_MT_EMBER                          171
#define MAPSEC_BERRY_FOREST                      172
#define MAPSEC_ICEFALL_CAVE                      173
#define MAPSEC_ROCKET_WAREHOUSE                  174
#define MAPSEC_TRAINER_TOWER_2                   175
#define MAPSEC_DOTTED_HOLE                       176
#define MAPSEC_LOST_CAVE                         177
#define MAPSEC_PATTERN_BUSH                      178
#define MAPSEC_ALTERING_CAVE_FRLG                179
#define MAPSEC_TANOBY_CHAMBERS                   180
#define MAPSEC_THREE_ISLE_PATH                   181
#define MAPSEC_TANOBY_KEY                        182
#define MAPSEC_BIRTH_ISLAND_FRLG                 183
#define MAPSEC_MONEAN_CHAMBER                    184
#define MAPSEC_LIPTOO_CHAMBER                    185
#define MAPSEC_WEEPTH_CHAMBER                    186
#define MAPSEC_DILFORD_CHAMBER                   187
#define MAPSEC_SCUFIB_CHAMBER                    188
#define MAPSEC_RIXY_CHAMBER                      189
#define MAPSEC_VIAPOIS_CHAMBER                   190
#define MAPSEC_EMBER_SPA                         191
#define MAPSEC_SPECIAL_AREA                      192
#define MAPSEC_AQUA_HIDEOUT                      193
#define MAPSEC_MAGMA_HIDEOUT                     194
#define MAPSEC_MIRAGE_TOWER                      195
#define MAPSEC_BIRTH_ISLAND                      196
#define MAPSEC_FARAWAY_ISLAND                    197
#define MAPSEC_ARTISAN_CAVE                      198
#define MAPSEC_MARINE_CAVE                       199
#define MAPSEC_UNDERWATER_MARINE_CAVE            200
#define MAPSEC_TERRA_CAVE                        201
#define MAPSEC_UNDERWATER_105                    202
#define MAPSEC_UNDERWATER_125                    203
#define MAPSEC_UNDERWATER_129                    204
#define MAPSEC_DESERT_UNDERPASS                  205
#define MAPSEC_ALTERING_CAVE                     206
#define MAPSEC_NAVEL_ROCK                        207
#define MAPSEC_TRAINER_HILL                      208
#define MAPSEC_NONE                              209
#define MAPSEC_COUNT                             210

#define KANTO_MAPSEC_START  MAPSEC_PALLET_TOWN
#define KANTO_MAPSEC_END    MAPSEC_SPECIAL_AREA

#endif // GUARD_CONSTANTS_REGION_MAP_SECTIONS_PORYMAP_H
