ViridianCity_House1_Khanto_MapScripts::
	.byte 0

ViridianCity_House1_Khanto_EventScript_OldMan::
	msgbox ViridianCity_House1_Khanto_Text_OldMan, MSGBOX_NPC
	end

ViridianCity_House1_Khanto_Text_OldMan:
	.string "Welcome to VIRIDIAN CITY!\p"
	.string "This city has a great GYM, but\n"
	.string "the LEADER is away often.\p"
	.string "Make sure you visit the POKeMON\n"
	.string "CENTER to heal your team!$"
