Route21_Khanto_MapScripts::
# 3 "data/maps/Route21_Khanto/scripts.pory"
	map_script MAP_SCRIPT_ON_TRANSITION, Route21_Khanto_MapScripts_MAP_SCRIPT_ON_TRANSITION
# 5 "data/maps/Route21_Khanto/scripts.pory"
	map_script MAP_SCRIPT_ON_RESUME, Route21_Khanto_MapScripts_MAP_SCRIPT_ON_RESUME
	.byte 0

Route21_Khanto_MapScripts_MAP_SCRIPT_ON_TRANSITION:
	return

Route21_Khanto_MapScripts_MAP_SCRIPT_ON_RESUME:
	return

