ViridianCity_Khanto_MapScripts::
	.byte 0

ViridianCity_Khanto_EventScript_OldMan::
	msgbox ViridianCity_Khanto_Text_OldMan, MSGBOX_NPC
	end

ViridianCity_Khanto_Text_OldMan:
	.string "This is VIRIDIAN CITY!\p"
	.string "You look like a TRAINER on\n"
	.string "a journey. The road to PEWTER\n"
	.string "goes through VIRIDIAN FOREST.$"

ViridianCity_Khanto_EventScript_Beauty::
	msgbox ViridianCity_Khanto_Text_Beauty, MSGBOX_NPC
	end

ViridianCity_Khanto_Text_Beauty:
	.string "The GYM LEADER in VIRIDIAN\n"
	.string "isn't around much, but the\n"
	.string "GYM itself is worth seeing!$"

ViridianCity_Khanto_EventScript_CitySign::
	msgbox ViridianCity_Khanto_Text_CitySign, MSGBOX_SIGN
	end

ViridianCity_Khanto_Text_CitySign:
	.string "VIRIDIAN CITY\n"
	.string "The Garden of the Continent$"

ViridianCity_Khanto_EventScript_GymSign::
	msgbox ViridianCity_Khanto_Text_GymSign, MSGBOX_SIGN
	end

ViridianCity_Khanto_Text_GymSign:
	.string "VIRIDIAN CITY POKeMON GYM\n"
	.string "LEADER: GIOVANNI\p"
	.string "The GYM is currently closed.$"

ViridianCity_Khanto_EventScript_TrainerTips1::
	msgbox ViridianCity_Khanto_Text_TrainerTips1, MSGBOX_SIGN
	end

ViridianCity_Khanto_Text_TrainerTips1:
	.string "TRAINER TIPS\p"
	.string "Catch POKeMON and expand your\n"
	.string "collection.$"

ViridianCity_Khanto_EventScript_TrainerTips2::
	msgbox ViridianCity_Khanto_Text_TrainerTips2, MSGBOX_SIGN
	end

ViridianCity_Khanto_Text_TrainerTips2:
	.string "TRAINER TIPS\p"
	.string "The battle moves of POKeMON are\n"
	.string "limited by their POWER POINTS, PP.$"

ViridianCity_Khanto_EventScript_GymDoor::
	msgbox ViridianCity_Khanto_Text_GymDoor, MSGBOX_SIGN
	end

ViridianCity_Khanto_Text_GymDoor:
	.string "VIRIDIAN GYM's doors are locked…$"
